### ISSUE TITLE
Move to Markdown

### ISSUE THREAD

**Issue by timmens** [OpenSourceEconomics/econ-project-templates#112]
Translate all RST files to Markdown.

**Comment by timmens** [comment]
@mj023

Please use the script we have developed to translate all RST files in this repo to Markdown. Since there are a few exceptions where the script does not yield a one-to-one mapping in the rendered Markdown, please adjust these cases by hand and write down for which cases such an intervention was necessary.

**Workflow:**
Please create a pull request from a fork. If you feel unsure about pull requests read [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

If you have any questions write them here or via email.

**Comment by hmgaudecker** [comment]
Thanks guys!!!

> **Workflow:** Please create a pull request from a fork. If you feel unsure about pull requests read [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

@mj023: I just gave you access to this repo, so just clone it and set up a PR directly from a branch (@timmens, oftentimes I find it easier to make some smaller changes to a PR myself during review rather than describing what I think would be best, particularly for documentation. IIRC, that is hard/annoying when the PR comes from a fork).

**Comment by hmgaudecker** [comment]
Fixed in #117, thanks again @mj023 !
